server:
  #  port: ${random.int[8011,8020]}
  port: 8000
  tomcat:
    basedir: E:\temp\

spring:
  application:
    name: secondkill-zuul
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

ribbon:
  ReadTimeout: 5000
# 请求连接超时时间
  ConnectTimeout: 1000


zuul:
  routes:
    secondkill-user:
      path: /user/**
      serviceId: secondkill-user
      stripPrefix: false
    secondkill-order:
      path: /order/**
      serviceId: secondkill-order
      stripPrefix: false
    secondkill-auth:
      path: /auth/**
      serviceId: secondkill-auth
      stripPrefix: false
    secondkill-good:
      path: /goods/**
      serviceId: secondkill-goods
      stripPrefix: false
  prefix: /api
  sensitiveHeaders: "*"
  strip-prefix: true
auth:
  publicKey:
    MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDAmK932VuscbhXmymX4WRyPOnIKlxYEOVJHmSx
    AP+cpVnrJB2nm57YqkNtrAhTwfrUWpccMIOUHsJ8AK8GcMBSLkLsbo/H0Bb1aTJ7e/PTeI6/3JF0
    T+LKH0VTSiTDA7Xrsm6fFZSeC3TE/wSUuvEuxKoG7pdRhtuerxGFrkygFQIDAQAB


# Redis服务器地址
redis:
  host: 127.0.0.1
  # Redis服务器连接端口
  port: 6379
  # Redis服务器连接密码（默认为空）
  password: null
  timeout: 30000
  # 连接池最大连接数（使用负值表示没有限制）
  maxTotal: 30
  # 连接池中的最大空闲连接
  maxIdle: 10
  numTestsPerEvictionRun: 1024
  timeBetweenEvictionRunsMillis: 30000
  minEvictableIdleTimeMillis: 1800000
  softMinEvictableIdleTimeMillis: 10000
  # 连接池最大阻塞等待时间（使用负值表示没有限制）
  maxWaitMillis: 1500
  testOnBorrow: true
  testWhileIdle: true
  blockWhenExhausted: false
  JmxEnabled: true



