server:
#  port: ${random.int[8011,8020]}
  port: 8021
  tomcat:
    basedir: E:\temp\

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: secondkill-goods
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql:///choy_ms?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
      username: root
      password: 86598659yu
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true

  rabbitmq:
    port: 5672
    host: 127.0.0.1
    username: guest
    password: guest

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

service-url:
  nacos-user-service: http://secondkill-user

auth:
  publicKey:
    MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDAmK932VuscbhXmymX4WRyPOnIKlxYEOVJHmSx
    AP+cpVnrJB2nm57YqkNtrAhTwfrUWpccMIOUHsJ8AK8GcMBSLkLsbo/H0Bb1aTJ7e/PTeI6/3JF0
    T+LKH0VTSiTDA7Xrsm6fFZSeC3TE/wSUuvEuxKoG7pdRhtuerxGFrkygFQIDAQAB

# Redis服务器地址
redis:
  host: 127.0.0.1
# Redis服务器连接端口
  port: 6379
# Redis服务器连接密码（默认为空）
  password: null
  timeout: 30000
# 连接池最大连接数（使用负值表示没有限制）
  maxTotal: 30
# 连接池中的最大空闲连接
  maxIdle: 20
  numTestsPerEvictionRun: 1024
  timeBetweenEvictionRunsMillis: 30000
  minEvictableIdleTimeMillis: 1800000
  softMinEvictableIdleTimeMillis: 10000
# 连接池最大阻塞等待时间（使用负值表示没有限制）
  maxWaitMillis: 1500
  testOnBorrow: true
  testWhileIdle: true
  blockWhenExhausted: false
  JmxEnabled: true

logger:
  level:
    com.secondkill: debug